apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: session-service
  name: session-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: session-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../../docker-compose.yml convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: session-service
    spec:
      containers:
        - env:
            - name: DB_ADDRESS
          image: session-service
          name: session-service
          ports:
            - containerPort: 6969
          resources: {}
      restartPolicy: Always
status: {}
